version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: design_patterns_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: